#!/usr/bin/env bash
###########################################################################
##                     Copyright (C) 2018 wystan
##
##       filename: genkey.sh
##    description:
##        created: 2018-02-07 20:26:13
##         author: wystan
##
###########################################################################

#openssl genrsa -out privkey.pem 2048
#openssl req -new -x509 -key privkey.pem -out cacert.pem -days 1095 -subj /C=CN/ST=BJ/L=Beijing/O=TAL/OU=LiveCloud/CN=wystan/emailAddress=wystan@china.com
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:1024 -keyout privateKey.key -out certificate.crt -subj /C=CN/ST=BJ/L=Beijing/O=TAL/OU=LiveCloud/CN=wystan/emailAddress=wystan@china.com
openssl dhparam -out dh_param_2048.pem 2048

###########################################################################
