#!/usr/bin/env bash
###########################################################################
##                     Copyright (C) 2018 wystan
##
##       filename: genkey.sh
##    description:
##        created: 2018-02-07 20:26:13
##         author: wystan
##
###########################################################################

openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout cakey.pem -out cacert.pem -subj /C=CN/ST=BJ/L=Beijing/O=TAL/OU=LiveCloud/CN=wystan/emailAddress=wystan@china.com

###########################################################################
